### ISSUE TITLE
Comportamiento basico del ArenaCharacter

### ISSUE THREAD

**Issue by AlbertMontagutCasero** [Jendoliver/dam2project-ue4#32]
Hacer que los ArenaCharacter puedan:
- [x] Movimiento basico W,A,S,D + Camera Movement
- [x] Agacharse
- [x] Saltar

**Comment by AlbertMontagutCasero** [comment]
Falta hacer el merge de los proyectos.

**Comment by Jendoliver** [comment]
@AlbertMontagutCasero PR develop
