### ISSUE TITLE
Arena Character Getters

### ISSUE THREAD

**Issue by Magners** [Jendoliver/dam2project-ue4#39]
Implement the following getters:

- [x] GetMaxHealth
- [x] GetCurrentHealth
- [x] GetPercentHealth

- [x] GetPercentUltimate

- [x] GetMaxAmmo
- [x] GetCurrentAmmo

**Comment by Jendoliver** [comment]
I'm on it brot 🥇

**Comment by Jendoliver** [comment]
Pushed some of these to dev right now @Magners

**Comment by Magners** [comment]
@Jendoliver Health UI Implemented and Widgets for ultimate and ammo ready for when Getters implemented

**Comment by Jendoliver** [comment]
@Magners nice fam, please merge your branch as it is right now if possible and I'll implement the missing getters. I've thought about giving the weapons a custom widget subclass UPROPERTY which implements these methods, but I have to try it so it'd be nice to have your branch merged ASAP to avoid merging more content in the future. 

As a side note, I would suggest you to try to keep your branches as short as possible (maybe one branch per widget) so you'll be integrating your changes more frequently. This methodology is safer than keeping branches stale for a longer time, which is likely to cause more conflicts in the mid run. Anyway, good job! 😄
